### ISSUE TITLE
Text box glitch?

### ISSUE THREAD

**Issue by nothanksok** [valrus/undertale-dialog-generator#13]
Sometimes when you do dots, (.....) it will stretch out beyond the screen, or screw with the letters! just fwi

**Comment by valrus** [comment]
More detail and/or a screenshot would help! But I'll investigate too.

**Comment by nothanksok** [comment]
Its been fixed!

On Sun, Dec 20, 2015 at 8:08 PM, Ian McCowan <notifications@github.com>
wrote:

> More detail and/or a screenshot would help! But I'll investigate too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valrus/undertale-dialog-generator/issues/13#issuecomment-166175420>
> .
>



-- 
[image: Phantom-chibi by seantriana] Here, Have some Danny
~Miranda

**Comment by valrus** [comment]
Cool, thanks for the update!
