### ISSUE TITLE
I think there may be a glitch with the secret

### ISSUE THREAD

**Issue by knucklejoe** [valrus/undertale-dialog-generator#33]
For some reason the secret cheat code refuses to work, when I have it completely right. So  I think it glitched or something.

**Comment by Hyper2500** [comment]
Try refreshing, make sure it's definitely on Caps Lock and then E then X.
![image](https://cloud.githubusercontent.com/assets/17166756/13015047/d50dc9fa-d1ae-11e5-9e80-3da64b449c9c.png) It works perfectly for me

**Comment by valrus** [comment]
Let me know if you get it working, @knucklejoe. If not, you need to provide some details (your browser/OS, for starters) for me to have any hope of fixing it.

**Comment by knucklejoe** [comment]
dont worry about it, i just got the cheatcode wrong.

**Comment by stefan72097** [comment]
What is the cheat code? Please, I need some Sans faces for an animation.

**Comment by valrus** [comment]
It's in the screenshot in this very thread. Please don't comment on closed issues, hit me up on Twitter if you have questions.
