### ISSUE TITLE
Annoying Dog?

### ISSUE THREAD

**Issue by Hyper2500** [valrus/undertale-dialog-generator#37]
Ever since IDTHV was released, I always thought it would be interesting to have Annoying Dog as a character.

**Comment by valrus** [comment]
Not likely. For the most part I try to stay canon and only support characters who actually have dialog boxes in the game. I know that some of what's in IDTHV skirts the bounds of this rule but: Annoying Dog just isn't that interesting a character to me, the character selection UI is pretty full at this point, and I want to leave some things for people to have to do themselves. It shouldn't be hard to throw together an Annoying Dog dialog box using my tool and an image editor if you're so inclined.
