### ISSUE TITLE
W.D Gaster?

### ISSUE THREAD

**Issue by IndieIzzy** [valrus/undertale-dialog-generator#40]
Could you add a Dr.W.D Gaster option? Doesn't have to be in windings or anything, I was just wondering.

Thanks!

**Comment by ev1l0rd** [comment]
He only adds characters that have official faces in the game. A wingdings font however would be pretty cool.

**Comment by IndieIzzy** [comment]
Ooh, right. I was just wondering. Thanks!

**Comment by valrus** [comment]
Yeah, having never actually seen Gaster in the game I'm not too enthusiastic about adding him.

**Comment by IndieIzzy** [comment]
Ah, that's true. You can only see him through messing with the game
manually. Although it is hinted that he worked with sans at some point, but
other than that he's not really a prominent character.

**Comment by ev1l0rd** [comment]
That's only partially correct, he appears based on your fun value, which
since the 1.0.1 update no longer has to be capitalized. (That being said,
the chance that you will see Gaster in default gameplay is practically
zero.)

**Comment by IndieIzzy** [comment]
Oh, I didn't know that. I wonder if anything will be revealed about him.
Apparently Toby Fox was considering another game or something (although I'm
gonna remain sceptical until I see anything come up directly from Toby
Fox), so maybe if it's got anything to do with Undertale then it might shed
some light on who gaster is. Or was.
