### ISSUE TITLE
Change Characters mid text box.

### ISSUE THREAD

**Issue by Hyper2500** [valrus/undertale-dialog-generator#42]
In the second or third text box, completely switching characters to have the characters have a conversation for lack of a better word. Like : 
Papyrus
Undyne
Papyrus

Or

Toriel 
Flowey
Toriel

Something like that.

**Comment by valrus** [comment]
Yeah, this is something I'd like to do at some point. I don't have a 
good idea of how hard it is just yet.

**Comment by valrus** [comment]
Oh, this was done a long time ago and I forgot to close this. Closing now.
