### ISSUE TITLE
Cheat code doesn't work on Firefox

### ISSUE THREAD

**Issue by Leo40Git** [valrus/undertale-dialog-generator#43]
As the title says. Typing "EX" with Caps Lock on does nothing on Firefox, but works on Microsoft Edge (yes I'm using Win10).

**Comment by ev1l0rd** [comment]
Duplicate of #36

**Comment by Leo40Git** [comment]
@ev1l0rd Oh, whoops.

**Comment by valrus** [comment]
Ahhh. We had some fun times in this thread, didn't we?
