### ISSUE TITLE
(suggestion) merging with bitwise-guy's text box generator

### ISSUE THREAD

**Issue by kitestarGL** [valrus/undertale-dialog-generator#44]
saw a few person's requests about "faceless textbox" and "colored text" and thought that you should get a hold of the gent who made this: http://bitwise-guy.net/assorted/underlog/ and merge your generators together, you'll have your faceless and colored boxes and he'll have faces

**Comment by ev1l0rd** [comment]
It doesn't work like that. IDTHV is build on the Elm language. Underlog on the other hand just uses PHP to generate a text box.

**Comment by valrus** [comment]
Yeah, thanks for bringing that other site to my attention; a little healthy competition is always good! But @ev1l0rd is right, merging the two sites wouldn't be any easier than just coding up a new one from scratch.
