### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by WinterHope15** [valrus/undertale-dialog-generator#46]
1. Is it possible to put more than one character in? (like 2 or more characters having a convorsation)
aaand
2. Is it possible to put more than 3 boxes?

**Comment by valrus** [comment]
1. Not yet, but this is on the docket as issue #42. It will probably be the next feature I try to add, but I don't know when that will be.
2. No, and I don't plan to allow it. You should, of course, be able to generate more than one image and combine them in an image editor without much difficulty.
