### ISSUE TITLE
only lower caps on sans dialogue

### ISSUE THREAD

**Issue by MrFluffCat** [valrus/undertale-dialog-generator#50]
In the game, the sans dialogue usually is in all lower case, but there are some instances where he does have words capitalized. And for some reason, I can't type in capital letters when I have sans selected. If you could fix this, that would be awesome.

**Comment by valrus** [comment]
You can't type caps as Sans because I designed it that way. :)

I don't recall any places in the game where Sans has capitalized text.
Refresh my memory? It's probably not hard to undo this but I do like the
"flavor" of having Sans speak in lowercase even if you try to make him use
caps.

**Comment by ev1l0rd** [comment]
Nothing much, most of the time it is lowercase. Sometimes he mixes up
things like writing I in uppercase. Just goes to show how lazy he is.

On 7 April 2016 at 18:47, Ian McCowan <notifications@github.com> wrote:

> You can't type caps as Sans because I designed it that way. :)
>
> I don't recall any places in the game where Sans has capitalized text.
> Refresh my memory? It's probably not hard to undo this but I do like the
> "flavor" of having Sans speak in lowercase even if you try to make him use
> caps.
>
> On Wed, Apr 6, 2016 at 9:40 PM, MrFluffCat <notifications@github.com>
> wrote:
>
> > In the game, the sans dialogue usually is in all lower case, but there
> are
> > some instances where he does have words capitalized. And for some
> reason, I
> > can't type in capital letters when I have sans selected. If you could fix
> > this, that would be awesome.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/valrus/undertale-dialog-generator/issues/50>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/valrus/undertale-dialog-generator/issues/50#issuecomment-206988669>
>



-- 
Vriendelijke groet van Valentijn Vermeij

**Comment by valrus** [comment]
OK, I'm calling this "as designed." Sans speaks in lowercase, any time he doesn't it's wrong, this is official IDTHV canon now, I proclaim it thus.
