### ISSUE TITLE
(Suggestion) More languages need to be added, preferably Korean and Japanese.

### ISSUE THREAD

**Issue by Ironcreater** [valrus/undertale-dialog-generator#52]
Now idc what you say, languages are able to be added. You can't say you just can't cause there is millions of ways to do it.

1.Volunteers. [Yes, I know Japanese so I can help out.]

2.[Pls no] Google Translate.

3.[yee] Just learn the language.

4.Break the barrier of English, just break the barrier of only english and free Asri-san. Worry about pixelation for Sans and Papyrus later.

5.Get a skele-ton of work done.

Pls reply for multi language

燃やす。

**Comment by valrus** [comment]
This is not the way to ask for something from a person doing work for free and for fun in his spare time while also working a full-time job. I agree it's a shame that IDTHV only supports a subset of Latin-script, and I agree that it's not 100% unfeasible to support other languages. But it's a huge undertaking, easily equal to the total amount of work I've done on this project so far, and even Undertale _itself_ hasn't been translated into any other languages. Not a single one of the fonts I use even contains any characters outside CP-1252.

If this is that important to you, fork this project, do some of the work you're demanding, and submit a pull request. If that's too much work for you, think about how rude it is of you to come in here with that peremptory attitude and instruct me to do it.

**Comment by Ironcreater** [comment]
Sorry, it's just fnafb changed my attitude alot.
:l
