### ISSUE TITLE
Cheat code doesn't work with SHIFT - only with caps lock

### ISSUE THREAD

**Issue by mateon1** [valrus/undertale-dialog-generator#53]
When I enter the EX cheat code, I have to use caps lock for it to work. Typing it in capitals with shift doesn't trigger it.
My environment is Chrome on Windows 10 x64

**Comment by valrus** [comment]
I see why this is and I think I can fix it without too much trouble. In the meantime, you can actually just enter the code in lower case. SHH DON'T TELL ANYONE.

**Comment by valrus** [comment]
Should be fixed by 924adb170812458e58227bb6280c72b728fb9e43.
