### ISSUE TITLE
CopyPasta

### ISSUE THREAD

**Issue by Arinerron** [valrus/undertale-dialog-generator#60]
Is that really required :P

**Comment by valrus** [comment]
No, but if I was making decisions based on what is "required" IDTHV wouldn't exist at all.

**Comment by Arinerron** [comment]
:P

**Comment by valrus** [comment]
For fun? For the lulz? Because I noticed a bunch of people spamming copypasta and I wanted them to know I saw them doing it?

**Comment by Arinerron** [comment]
Oh, okay. That's the response I was looking for :P
