### ISSUE TITLE
Open API

### ISSUE THREAD

**Issue by henry232323** [valrus/undertale-dialog-generator#68]
Is it possible to get an open use API for this? Without reverse engineering it of course, I'd like to be able to get these from a quick get request on the API.

**Comment by valrus** [comment]
There's really only one endpoint that matters and that's the ``/submit`` URL.

My poor website is apparently being hit too hard at the moment for me to test this, but here's an example using the Python requests module:
```python
r = requests.get(baseurl, params={'text': 'Hi!\nThis is an API call!', 'moodImg': ['images/sprites/Papyrus/0.png']})
```

That request generates the following URL:
```
http://thehotvoice.mccowan.space/?text=Hi%21%0AThis+is+an+API+call%21&moodI
mg=images%2Fsprites%2FPapyrus%2F0.png
```

so if you're using something other than the Python requests module you just need to make a URL like that. You'll get back a b64-encoded PNG file.

It's not designed to be accessed like this so if you do it wrong the error message might not be very helpful. In particular, the text you pass in is split into groups of 3 lines, each of which groups goes into a dialog box. You need to pass one moodImg param for each box. And the moodImg arguments are just numbers (the path construction should be pretty obvious) so you need to figure out what number corresponds to which picture. (You can just look in [here](https://github.com/valrus/undertale-dialog-generator/tree/master/src/static/images/sprites) to find that out!)

That's about it. LMK if that's not enough to go on.

**Comment by henry232323** [comment]
Awesome thanks!

**Comment by henry232323** [comment]
Hmm you'll probably get the same result if you use your link, but using yours or other requests, it just directs me to the http://thehotvoice.mccowan.space/ page, and it seems trying anything on the `/submit` endpoint, it 404's

**Comment by valrus** [comment]
Alright, I got it working. The working example URL that worked for me:
```
'http://ianmccowan.nfshost.com/undertale/submit?text=Hi%21%0AThis+is+an+API+call%21&moodImg=%2Fundertale%2Fstatic%2Fimages%2Fsprites%2FPapyrus%2F0.png
```

For some reason it doesn't like you to do it with the `thehotvoice` URL; I guess the redirect I'm using with my domain doesn't play well with requests.

**Comment by valrus** [comment]
Oh, actually, this works too:
```
http://thehotvoice.mccowan.space/undertale/submit?text=Hi%21%0AThis+is+an+API+call%21&moodImg=%2Fundertale%2Fstatic%2Fimages%2Fsprites%2FPapyrus%2F0.png
```

Note that I had to add a couple extra path components to the sprite image as well.

**Comment by henry232323** [comment]
Oh there we go awesome, thanks!

**Comment by valrus** [comment]
No problem. Closing this now.

**Comment by henry232323** [comment]
Oh just to let you know, in testing, I found that `http://ianmccowan.nfshost.com` yielded the actual result `http://thehotvoice.mccowan.space` popped it in an `<iframe>`

**Comment by valrus** [comment]
What about http://thehotvoice.mccowan.space/undertale ?

**Comment by henry232323** [comment]
On both I was using `/undertale/submit`

**Comment by henry232323** [comment]
Did you say you were forewarning the domain instead of DNS?

**Comment by henry232323** [comment]
Forewarding*
